### ISSUE TITLE
Decompression fails on this file

### ISSUE THREAD

**Issue by JetForMe** [eloj/lzw-eddy#5]
I'm hoping to use your code to decompress TIFF files I parse with my custom parser. The attached file is a block of lzw-compressed data, but I don't know anything more than that. It should decompress to 1048576 bytes.

Note that the attached file is zipped, because GitHub wouldn't accept the `.lzw` suffix. Unzip it, and it should be 735,782 bytes of lzw-compressed data. But when I try to decompress it, I get a -2 result.

[data.lzw.zip](https://github.com/user-attachments/files/16536520/data.lzw.zip)

I'm about to try zlib on it. I'm 99% sure it's valid data, and for sure existing TIFF readers can decompress it. But I may have made a mistake somewhere.

**Comment by eloj** [comment]
I've never investigated what 'parameterization' of LZW "TIFF" use, but compatibility with TIFF is neither a goal nor something I promise for this library.

**Comment by JetForMe** [comment]
Fair enough. I had just hoped you might be able to suggest something to look at. I was looking for a simple source solution due to the complexities of building for my varied targets, and your header-only implementation made that very easy. But I might be able to make zlib work.
